### ISSUE TITLE
Fix display of time in the front end

### ISSUE THREAD

**Issue by magolimbo** [Gabriellanaro/Pause#2]
Im creating this thread just to test this github feature, maybe it's useful.

now the front end of the feed page looks like this.
![image](https://github.com/user-attachments/assets/df0fa4bd-660e-43f0-bd5e-88c6b0785897)

time is displayed in a weird way, and we want it to be displayed like this
![image](https://github.com/user-attachments/assets/136a1eed-3ca4-43c2-bd62-ea5e23ed472e)

**Comment by paulagambus** [comment]
@magolimbo @Gabriellanaro @valemorra I will work on it tomorrow or Wednesday :)
